name: Build RPM

on:
  workflow_dispatch:
    inputs:
      businessUnit:
        description: 'Business Unit'
        required: true
        type: choice
        options:
        - bmes
        - bmfr
        - bmit
        - bmpl
        - zdfr

env:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -Dci-cd -s ./src/main/build/settings-maven.xml"
  INSTALL_PROPERTIES_PATH: src/main/installer/properties/config.properties
  RPMNAME: PRO-REPLENISHMENT-DATA-EXPORTER-BATCH-

jobs:
  deploy:
    if: (github.ref != 'refs/heads/master')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        env:
          JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
          JFROG_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
          JFROG_REGISTRY: ${{ secrets.JFROG_REGISTRY }}
          JFROG_API: ${{ secrets.JFROG_API }}
          # Business Unit configuration
          MVN_BU_NAME: ${{ github.event.inputs.businessUnit }}
          #RPM_SUFFIX: ${{ fromJSON(secrets.BU_CONFIG)[github.event.inputs.businessUnit].rpmSuffix }}
          #PKBU: ${{ fromJSON(secrets.BU_CONFIG)[github.event.inputs.businessUnit].pkBu }}
        run: |
          sudo apt-get install rpm -y
          RPM_SUFFIX=`jq .${{ github.event.inputs.businessUnit }}.rpmSuffix .github/build-rpm-config.json`
          echo $MVN_BU_NAME
          echo $RPM_SUFFIX
